apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
spec:
  replicas: 1
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "7080"
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: tasks
        component: infra
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: star-example-com-secrets
      containers:
      - image: gcr.io/myproj/tasks:v0.2.6
        ports:
        - containerPort: 7080
        - containerPort: 7443
        name: tasks
        volumeMounts:
          - mountPath: /etc/ssl
            name: secret-volume

