project_name: cue

gomod:
  proxy: true

builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/cue
  binary: cue
  ldflags:
    - -s -w
    # TODO: consider adding the following for a verbose mode
    # - -X cuelang.org/go/cmd/cue/cmd.version={{.Version}}
    # - -X cuelang.org/go/cmd/cue/cmd.commit={{.ShortCommit}}
    # - -X cuelang.org/go/cmd/cue/cmd.date={{.Date}}
    # - -X cuelang.org/cmd/cue/cmd.date={{.Env.GOVERSION}}
  goos:
    # File and Issue to request including other platforms.
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64

archives:
- name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  replacements:
  files:
    - LICENSE
    - README.md
    - doc/tutorial/**/*
    - doc/ref/spec.md
  format_overrides:
    - goos: windows
      format: zip

release:
  disable: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^test:'

brews:
- tap:
    owner: cuelang
    name: homebrew-tap
  commit_author:
    name: cue-bot
    email: noreply@cuelang.org
  homepage: "https://cuelang.org"
  description: "CUE is an open source data constraint language which aims to simplify tasks involving defining and using data."
  test: |
    system "#{bin}/cue version"


dockers:
- image_templates:
  - "docker.io/cue-lang/cue:{{ .Version }}-amd64"
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/cue-lang/cue
  - --label=org.opencontainers.image.source=https://github.com/cue-lang/cue
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache 2.0
- image_templates:
  - "docker.io/cue-lang/cue:{{ .Version }}-arm64"
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/cue-lang/cue
  - --label=org.opencontainers.image.source=https://github.com/cue-lang/cue
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache 2.0

docker_manifests:
- name_template: docker.io/cue-lang/cue:{{ .Version }}
  image_templates:
  - docker.io/cue-lang/cue:{{ .Version }}-amd64
  - docker.io/cue-lang/cue:{{ .Version }}-arm64v8
- name_template: docker.io/cue-lang/cue:latest
  image_templates:
  - docker.io/cue-lang/cue:{{ .Version }}-amd64
  - docker.io/cue-lang/cue:{{ .Version }}-arm64v8
