// Code generated by cue get go. DO NOT EDIT.

// Package cli provides tasks dealing with a console.
//
// These are the supported tasks:
//
//     // Print sends text to the stdout of the current process.
//     Print: {
//     	kind: "tool/cli.Print"
//
//     	// text is the text to be printed.
//     	text: string
//     }
//
package cli
