// Code generated by gocode.Generate; DO NOT EDIT.

package pkg1

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/encoding/gocode/gocodec"
	_ "cuelang.org/go/pkg"
)

var cuegenvalMyStruct = cuegenMake("MyStruct", &MyStruct{})

// Validate validates x.
func (x *MyStruct) Validate() error {
	return cuegenCodec.Validate(cuegenvalMyStruct, x)
}

// Complete completes x.
func (x *MyStruct) Complete() error {
	return cuegenCodec.Complete(cuegenvalMyStruct, x)
}

var cuegenvalOtherStruct = cuegenMake("OtherStruct", &OtherStruct{})

// Validate validates x.
func (x *OtherStruct) Validate() error {
	return cuegenCodec.Validate(cuegenvalOtherStruct, x)
}

var cuegenvalString = cuegenMake("String", nil)

// ValidateCUE validates x.
func (x String) ValidateCUE() error {
	return cuegenCodec.Validate(cuegenvalString, x)
}

var cuegenvalSpecialString = cuegenMake("SpecialString", nil)

// ValidateSpecialString validates x.
func ValidateSpecialString(x string) error {
	return cuegenCodec.Validate(cuegenvalSpecialString, x)
}

var cuegenvalPtr = cuegenMake("Ptr", Ptr(nil))

// ValidatePtr validates x.
func ValidatePtr(x Ptr) error {
	return cuegenCodec.Validate(cuegenvalPtr, x)
}

var cuegenCodec, cuegenInstance_, cuegenValue = func() (*gocodec.Codec, *cue.Instance, cue.Value) {
	var r *cue.Runtime
	r = &cue.Runtime{}
	instances, err := r.Unmarshal(cuegenInstanceData)
	if err != nil {
		panic(err)
	}
	if len(instances) != 1 {
		panic("expected encoding of exactly one instance")
	}
	return gocodec.New(r, nil), instances[0], instances[0].Value()
}()

// Deprecated: cue.Instance is deprecated. Use cuegenValue instead.
var cuegenInstance = cuegenInstance_

// cuegenMake is called in the init phase to initialize CUE values for
// validation functions.
func cuegenMake(name string, x interface{}) cue.Value {
	f, err := cuegenValue.FieldByName(name, true)
	if err != nil {
		panic(fmt.Errorf("could not find type %q in instance", name))
	}
	v := f.Value
	if x != nil {
		w, err := cuegenCodec.ExtractType(x)
		if err != nil {
			panic(err)
		}
		v = v.Unify(w)
	}
	return v
}

// Data size: 605 bytes.
var cuegenInstanceData = []byte("\x01\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xff\x94RMo\xd3J\x14\x9dq\xf2\xa4\u7afe'\xf1\x03\x90.\xb3\x8aQ\xb1\x93H\xb0\xb0j\xe8\a\x05u\xd1&\xa2\x05!\x10\x8b\x89}\xe3\x8c\xea\u0318x\\\x1a\x95\x16(\xa5?\xbbF\xceG\x1b\x16,\xea\xd5\u0475\xcf=\xc7\xf7\x9c\xff\xaa_\x0ew\xaak\u01ab\xef\x8c=\xfb\xd6\xe0|M\xe9\xc2J\x1d\xd3Kie=\xe6\r\xde|c\x8c\xe5\x0e\xe3\u037e\xb4#\xbe\xc6\xf8?\xafTF\x05\xaf\xae\x18c\x0f\xab\x9f\x0e\xe7\xff\x7f\xfc\x14\x97\xe4\x0fU\xb6`^1^]2\u05aa~48\xff\xf7n~\u0278\u00db\arL\xf5\xa2\xe6l\b\x8c\xb1\x9b\xc6Qu\xcd\x1c\xcey\x10\x97\x94I\x9d\xfaf\x92\x06\xa9\tH\xc7&Q\xba\u01b1I(\xb0T\xd8DZ\x19\xe4\xc7ig\xf3\xa4\xcd9\x7fP\xc3`i\u074fK\xe27\u0387\\\xc6\xc72%\xac_\x02\xa8qn&\x16[\xe0\x8a{\bt\x05\xb8\xa2\xb0\x13\xa5\u04e2\x86ciG\x02<\x80\xfd\u985d\x94\xb1\r\xf1\f\u072d\x10q#\xea\xb4\xc1\xdd\x0e\x11\xa3\v\x11K+\xf0+>\x16\x89I\x05\xb8\xbd\x17!\xf6\xec\x88&s\x0e\xb8{!\u05b6\xba\xfe\xde\xcc\xd5>\xc19n\xa6\xa6\xb5\x1e\x9bq\x9e\x91\xa5hg\x01<X!.\xc5\x16\x86\xfc\x1d\xa3\xadT\xba\xd8\xd2\u04d6x/<p\xfb\xe1|o_\xc5\xc7\xf5V8\x9c}\x1a\xe2\xe2y\x14\t\xb1\xc43\xc1\x13\x99\xa9DZ\x8a\xde-\xc0\xce\xdb]\x0f\x0es\x8a\x95\u0316\xe4\xe8B\x14\U000c9633\xec4\xa7h\xee\u0083\xbdT\x9b\t\x1d\x8dT1\x93\x89.\xc4\xd0\x18\x01\xbd\xb1\xb2\xb7\xba\x88J[\\U~\xe2\x01\x04\x01\x1e\x18\xbd{\xaa\n\xabt\x8a_T\x96\xe1\x80\u040c\x95\xb5\x94\xa0,\xb0\xfewBU\xa06H\x9fKu\"3\xd2\x16_\x1b\xac-\xf8\xb0B\x0f\xf1l{y\x9a\xf3U\t5\U000c7966\xd3\xfa\u0614`\xa93*\n\xa4\xd3<S\xb1\xb2\xd9\x14I\xcbAF\x89\x0fCc\xc2\xda+\xf4\xed$\u012d\x10\xeb\xc4\xfd\xfd2\xb3*\u03e87lu\xda\x1e0\xe6\xac\u07e7D\x8b\x8av\xff\xac\xa8\\)h\xf7\xb6\xa0wm\x83e9f\xb1\xcb\x107:\xed6\xb8\x83\xbf\xe4/\a\xb1\xf0\xe0\x1c\xe6\u0447\xf8\xfc)0\xf6;\x00\x00\xff\xff\x93\xa4O\xea\xe3\x03\x00\x00")
