apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - name: main
    port: 9090
    protocol: TCP
    nodePort: 30900
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
      annotations:
        prometheus.io.scrape: "true"
    spec:
      containers:
      - image: prom/prometheus:v2.4.3
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--web.external-url=https://prometheus.example.com'
        ports:
        - name: web
          containerPort: 9090
        name: prometheus
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
