// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package openapi

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register("encoding/openapi", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{{
		Name: "MarshalSchema",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.StringKind},
			{Kind: adt.TopKind},
		},
		Result:      adt.StringKind,
		NonConcrete: true,
		Func: func(c *pkg.CallCtxt) {
			config, version, schema := c.Value(0), c.String(1), c.Schema(2)
			if c.Do() {
				c.Ret, c.Err = marshalSchema(c.OpContext(), config, version, schema)
			}
		},
	}},
	CUE: `{
	Config: {
		info:             _
		selfContained:    bool | *false
		expandReferences: bool | *false
	}
}`,
}
