// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package sprig

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register("sprig", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{{
		Name: "Title",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Title(s)
			}
		},
	}, {
		Name: "Untitle",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Untitle(s)
			}
		},
	}, {
		Name: "Substr",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			start, end, s := c.Int(0), c.Int(1), c.String(2)
			if c.Do() {
				c.Ret = Substr(start, end, s)
			}
		},
	}, {
		Name: "Nospace",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Nospace(s)
			}
		},
	}, {
		Name: "Trunc",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			n, s := c.Int(0), c.String(1)
			if c.Do() {
				c.Ret = Trunc(n, s)
			}
		},
	}, {
		Name: "Abbrev",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			width, s := c.Int(0), c.String(1)
			if c.Do() {
				c.Ret = Abbrev(width, s)
			}
		},
	}, {
		Name: "Abbrevboth",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			left, right, s := c.Int(0), c.Int(1), c.String(2)
			if c.Do() {
				c.Ret = Abbrevboth(left, right, s)
			}
		},
	}, {
		Name: "Initials",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Initials(s)
			}
		},
	}, {
		Name: "Wrap",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			width, s := c.Int(0), c.String(1)
			if c.Do() {
				c.Ret = Wrap(width, s)
			}
		},
	}, {
		Name: "WrapWith",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			width, sep, s := c.Int(0), c.String(1), c.String(2)
			if c.Do() {
				c.Ret = WrapWith(width, sep, s)
			}
		},
	}, {
		Name: "Indent",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			spaces, s := c.Int(0), c.String(1)
			if c.Do() {
				c.Ret = Indent(spaces, s)
			}
		},
	}, {
		Name: "Nindent",
		Params: []pkg.Param{
			{Kind: adt.IntKind},
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			spaces, s := c.Int(0), c.String(1)
			if c.Do() {
				c.Ret = Nindent(spaces, s)
			}
		},
	}, {
		Name: "Snakecase",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Snakecase(s)
			}
		},
	}, {
		Name: "Camelcase",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Camelcase(s)
			}
		},
	}, {
		Name: "Kebabcase",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Kebabcase(s)
			}
		},
	}, {
		Name: "Swapcase",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			s := c.String(0)
			if c.Do() {
				c.Ret = Swapcase(s)
			}
		},
	}, {
		Name: "Plural",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
			{Kind: adt.StringKind},
			{Kind: adt.IntKind},
		},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			one, many, count := c.String(0), c.String(1), c.Int(2)
			if c.Do() {
				c.Ret = Plural(one, many, count)
			}
		},
	}, {
		Name: "SemverCompare",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
			{Kind: adt.StringKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			constraint, version := c.String(0), c.String(1)
			if c.Do() {
				c.Ret, c.Err = SemverCompare(constraint, version)
			}
		},
	}, {
		Name: "Semver",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
		},
		Result: adt.StructKind,
		Func: func(c *pkg.CallCtxt) {
			version := c.String(0)
			if c.Do() {
				c.Ret, c.Err = Semver(version)
			}
		},
	}},
}
