package ci

import (
	"tool/file"
	"encoding/yaml"
)

command: gengithub: task: {
	for w in workflows {
		"\(w.file)": file.Create & {
			filename: "../../.github/workflows/\(w.file)"
			contents: """
				# Generated by internal/ci/ci_tool.cue; do not edit

				\(yaml.Marshal(w.schema))
				"""
		}
	}
}
