apiVersion: v1
kind: Service
metadata:
  name: maitred
  labels:
    app: maitred
    domain: prod
    component: frontend
spec:
  ports:
  - port: 7080
    protocol: TCP
    targetPort: 7080
    name: client
  selector:
    app: maitred
    domain: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maitred
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "7080"
      labels:
        app: maitred
        domain: prod
        component: frontend
    spec:
      containers:
      - image: gcr.io/myproj/maitred:v0.0.4
        ports:
        - containerPort: 7080
        name: maitred
        args: [
        ]
