name: "Documentation: alpha.cuelang.org"
title: "alpha.cuelang.org: "
description: "Report a problem with the alpha.cuelang.org documentation site"
labels: ["Triage", "NeedsInvestigation", "cuelang.org"]
body:

  - type: markdown
    attributes:
      value: |
        ## Please answer these questions before submitting your issue - thank you!

        ### For questions, please use one of our forums at <https://cuelang.slack.com/>.

  - type: textarea
    id: cue-version
    attributes:
      label: What page are you viewing on alpha.cuelang.org?
      description:
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: cue-actions
    attributes:
      label: What did you do?
      description:
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: cue-expected
    attributes:
      label: What did you expect to see?
      description:
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: cue-actual
    attributes:
      label: What did you see instead?
      description:
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: cue-extra
    attributes:
      label: Is there anything else you think we should know to help us understand your issue?
      description:
      placeholder:
      value:
    validations:
      required: false
