apiVersion: v1
kind: Service
metadata:
  name: download
  labels:
    app: download
    domain: prod
    component: infra
spec:
  ports:
  - port: 7080
    protocol: TCP
    targetPort: 7080
    name: client
  selector:
    app: download
    domain: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: download
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: download
        domain: prod
        component: infra
    spec:
      containers:
      - image: gcr.io/myproj/download:v0.0.2
        name: download
        ports:
        - containerPort: 7080
