// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go cuelang.org/go/cmd/cue/cmd/testdata/code/go/pkg3

package pkg3

import "cuelang.org/go/cmd/cue/cmd/testdata/code/go/pkg2:pkgtwo"

#Barzer: pkgtwo.#Barzer
