apiVersion: v1
kind: Service
metadata:
  name: waiter
  labels:
    app: waiter
    domain: prod
    component: frontend
spec:
  ports:
  - port: 7080
    protocol: TCP
    targetPort: 7080
    name: client
  selector:
    app: waiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiter
spec:
  replicas: 5
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "7080"
      labels:
        app: waiter
        domain: prod
        component: frontend
    spec:
      containers:
      - image: gcr.io/myproj/waiter:v0.3.0
        name: waiter
        ports:
        - containerPort: 7080
