apiVersion: v1
kind: Service
metadata:
  name: pastrychef
  labels:
    app: pastrychef
    domain: prod
    component: kitchen
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: client
  selector:
    app: pastrychef
    domain: prod
    component: kitchen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastrychef
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: pastrychef
        domain: prod
        component: kitchen
    spec:
      volumes:
      - name: pastrychef-disk
        gcePersistentDisk:
          pdName: pastrychef-disk
          fsType: ext4
      - name: secret-ssh-key
        secret:
          secretName: secrets
      containers:
      - image: gcr.io/myproj/pastrychef:v0.1.15
        volumeMounts:
        - name:  pastrychef-disk
          mountPath: /logs
        - mountPath: /etc/certs
          name: secret-ssh-key
          readOnly: true
        ports:
        - containerPort: 8080
        args: [
          "-env=prod",
          "-ssh-tunnel-key=/etc/certs/tunnel-private.pem",
          "-logdir=/logs",
          "-event-server=events:7788",
          "-reconnect-delay=1m",
          "-etcd=etcd:2379",
          "-recovery-overlap=10000"
        ]
        name: pastrychef
        livenessProbe:
          httpGet:
            path: /debug/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 3
