// Code generated by "stringer -type=Token -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[ATTRIBUTE-3]
	_ = x[literalBeg-4]
	_ = x[IDENT-5]
	_ = x[INT-6]
	_ = x[FLOAT-7]
	_ = x[STRING-8]
	_ = x[INTERPOLATION-9]
	_ = x[BOTTOM-10]
	_ = x[literalEnd-11]
	_ = x[operatorBeg-12]
	_ = x[ADD-13]
	_ = x[SUB-14]
	_ = x[MUL-15]
	_ = x[POW-16]
	_ = x[QUO-17]
	_ = x[AND-18]
	_ = x[OR-19]
	_ = x[LAND-20]
	_ = x[LOR-21]
	_ = x[BIND-22]
	_ = x[EQL-23]
	_ = x[LSS-24]
	_ = x[GTR-25]
	_ = x[NOT-26]
	_ = x[ARROW-27]
	_ = x[NEQ-28]
	_ = x[LEQ-29]
	_ = x[GEQ-30]
	_ = x[MAT-31]
	_ = x[NMAT-32]
	_ = x[LPAREN-33]
	_ = x[LBRACK-34]
	_ = x[LBRACE-35]
	_ = x[COMMA-36]
	_ = x[PERIOD-37]
	_ = x[ELLIPSIS-38]
	_ = x[RPAREN-39]
	_ = x[RBRACK-40]
	_ = x[RBRACE-41]
	_ = x[SEMICOLON-42]
	_ = x[COLON-43]
	_ = x[OPTION-44]
	_ = x[TILDE-45]
	_ = x[operatorEnd-46]
	_ = x[keywordBeg-47]
	_ = x[IF-48]
	_ = x[ELSE-49]
	_ = x[FOR-50]
	_ = x[IN-51]
	_ = x[LET-52]
	_ = x[TRY-53]
	_ = x[FALLBACK-54]
	_ = x[OTHERWISE-55]
	_ = x[FUNC-56]
	_ = x[TRUE-57]
	_ = x[FALSE-58]
	_ = x[NULL-59]
	_ = x[keywordEnd-60]
}

const _Token_name = "ILLEGALEOFCOMMENTATTRIBUTEliteralBegIDENTINTFLOATSTRINGINTERPOLATION_|_literalEndoperatorBeg+-*^/&|&&||===<>!<-!=<=>==~!~([{,....)]};:?~operatorEndkeywordBegifelseforinlettryfallbackotherwisefunctruefalsenullkeywordEnd"

var _Token_index = [...]uint8{0, 7, 10, 17, 26, 36, 41, 44, 49, 55, 68, 71, 81, 92, 93, 94, 95, 96, 97, 98, 99, 101, 103, 104, 106, 107, 108, 109, 111, 113, 115, 117, 119, 121, 122, 123, 124, 125, 126, 129, 130, 131, 132, 133, 134, 135, 136, 147, 157, 159, 163, 166, 168, 171, 174, 182, 191, 195, 199, 204, 208, 218}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
