// Code generated by "stringer -type=TagType -linecomment"; DO NOT EDIT.

package filetypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TagUnknown-0]
	_ = x[TagTopLevel-1]
	_ = x[TagSubsidiaryBool-2]
	_ = x[TagSubsidiaryString-3]
}

const _TagType_name = "TagUnknownTagTopLevelTagSubsidiaryBoolTagSubsidiaryString"

var _TagType_index = [...]uint8{0, 10, 21, 38, 57}

func (i TagType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TagType_index)-1 {
		return "TagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TagType_name[_TagType_index[idx]:_TagType_index[idx+1]]
}
