// Code generated by cuelang.org/go/internal/filetypes/generate.go from types.cue. DO NOT EDIT.

//go:build !cuebootstrap

package filetypes

func newTagTypes() map[string]TagType {
	return map[string]TagType{
		"allSchemas":           TagSubsidiaryBool,
		"auto":                 TagTopLevel,
		"binary":               TagTopLevel,
		"code":                 TagTopLevel,
		"compact":              TagSubsidiaryBool,
		"cue":                  TagTopLevel,
		"dag":                  TagTopLevel,
		"data":                 TagTopLevel,
		"go":                   TagTopLevel,
		"graph":                TagTopLevel,
		"indentSequences":      TagSubsidiaryBool,
		"ini":                  TagTopLevel,
		"json":                 TagTopLevel,
		"jsonl":                TagTopLevel,
		"jsonschema":           TagTopLevel,
		"koala":                TagSubsidiaryBool,
		"lang":                 TagSubsidiaryString,
		"openOnlyWhenExplicit": TagSubsidiaryBool,
		"openapi":              TagTopLevel,
		"pb":                   TagTopLevel,
		"proto":                TagTopLevel,
		"schema":               TagTopLevel,
		"strict":               TagSubsidiaryBool,
		"strictFeatures":       TagSubsidiaryBool,
		"strictKeywords":       TagSubsidiaryBool,
		"text":                 TagTopLevel,
		"textproto":            TagTopLevel,
		"toml":                 TagTopLevel,
		"xml":                  TagTopLevel,
		"yaml":                 TagTopLevel,
	}
}

// Aspect combinations shared by the entries below.
var (
	aspectSet0  = [numAspects]bval{aAttributes: dtrue, aCycles: dtrue, aData: dtrue, aDocs: dtrue, aReferences: dtrue}
	aspectSet1  = [numAspects]bval{aAttributes: dfalse, aCycles: dtrue, aData: dtrue, aDocs: dfalse, aReferences: dtrue}
	aspectSet2  = [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue}
	aspectSet3  = [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse}
	aspectSet4  = [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse}
	aspectSet5  = [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue, aStream: cfalse}
	aspectSet6  = [numAspects]bval{aAttributes: cfalse, aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aDocs: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: dfalse}
	aspectSet7  = [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: ctrue}
	aspectSet8  = [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse}
	aspectSet9  = [numAspects]bval{aConstraints: cfalse, aCycles: dtrue, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: dtrue}
	aspectSet10 = [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: cfalse}
	aspectSet11 = [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue}
	aspectSet12 = [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse}
	aspectSet13 = [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: dfalse}
	aspectSet14 = [numAspects]bval{aConstraints: cfalse, aCycles: dtrue, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue}
)

func newBuiltinRegistry() *registryData {
	return &registryData{
		base: [NumModes]*entry{
			Input: {
				aspects: aspectSet0,
			},
			Export: {
				aspects: aspectSet1,
			},
			Def: {
				aspects: aspectSet0,
			},
			Eval: {
				aspects: aspectSet1,
			},
		},
		extensions: [NumModes]map[string]*entry{
			Input: {
				"-": {
					encoding: sval{kind: dflt, value: "cue", excluded: []string{""}},
					aspects:  aspectSet2,
				},
				".cue": {
					encoding: sval{kind: concrete, value: "cue"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       sval{kind: concrete, value: "code"},
					interpretation: sval{kind: concrete, value: ""},
					aspects:        aspectSet2,
					tags: map[string]sval{
						"lang": {kind: concrete, value: "go"},
					},
				},
				".ini": {
					encoding:       sval{kind: concrete, value: "ini"},
					interpretation: sval{kind: dflt, value: "auto"},
					aspects:        aspectSet2,
				},
				".json": {
					encoding:       sval{kind: concrete, value: "json"},
					interpretation: sval{kind: dflt, value: "auto"},
					aspects:        aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ldjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ndjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".proto": {
					encoding: sval{kind: concrete, value: "proto"},
					aspects:  aspectSet2,
				},
				".textpb": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".toml": {
					encoding:       sval{kind: concrete, value: "toml"},
					interpretation: sval{kind: dflt, value: "auto"},
					aspects:        aspectSet2,
				},
				".txt": {
					encoding: sval{kind: concrete, value: "text"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".wasm": {
					encoding: sval{kind: concrete, value: "binary"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".xml": {
					encoding:       sval{kind: concrete, value: "xml"},
					interpretation: sval{kind: dflt, value: "auto"},
					aspects:        aspectSet2,
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding:       sval{kind: concrete, value: "yaml"},
					interpretation: sval{kind: dflt, value: "auto"},
					aspects:        aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding:       sval{kind: concrete, value: "yaml"},
					interpretation: sval{kind: dflt, value: "auto"},
					aspects:        aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
			Export: {
				"-": {
					encoding: sval{kind: dflt, value: "json", excluded: []string{""}},
					aspects:  aspectSet2,
				},
				".cue": {
					encoding: sval{kind: concrete, value: "cue"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       sval{kind: concrete, value: "code"},
					interpretation: sval{kind: concrete, value: ""},
					aspects:        aspectSet2,
					tags: map[string]sval{
						"lang": {kind: concrete, value: "go"},
					},
				},
				".ini": {
					encoding: sval{kind: concrete, value: "ini"},
					aspects:  aspectSet2,
				},
				".json": {
					encoding: sval{kind: concrete, value: "json"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ldjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ndjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".proto": {
					encoding: sval{kind: concrete, value: "proto"},
					aspects:  aspectSet2,
				},
				".textpb": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".toml": {
					encoding: sval{kind: concrete, value: "toml"},
					aspects:  aspectSet2,
				},
				".txt": {
					encoding: sval{kind: concrete, value: "text"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".wasm": {
					encoding: sval{kind: concrete, value: "binary"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".xml": {
					encoding: sval{kind: concrete, value: "xml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding: sval{kind: concrete, value: "yaml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding: sval{kind: concrete, value: "yaml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
			Def: {
				"-": {
					encoding: sval{kind: dflt, value: "cue", excluded: []string{""}},
					aspects:  aspectSet2,
				},
				".cue": {
					encoding: sval{kind: concrete, value: "cue"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       sval{kind: concrete, value: "code"},
					interpretation: sval{kind: concrete, value: ""},
					aspects:        aspectSet2,
					tags: map[string]sval{
						"lang": {kind: concrete, value: "go"},
					},
				},
				".ini": {
					encoding: sval{kind: concrete, value: "ini"},
					aspects:  aspectSet2,
				},
				".json": {
					encoding: sval{kind: concrete, value: "json"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ldjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ndjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".proto": {
					encoding: sval{kind: concrete, value: "proto"},
					aspects:  aspectSet2,
				},
				".textpb": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".toml": {
					encoding: sval{kind: concrete, value: "toml"},
					aspects:  aspectSet2,
				},
				".txt": {
					encoding: sval{kind: concrete, value: "text"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".wasm": {
					encoding: sval{kind: concrete, value: "binary"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".xml": {
					encoding: sval{kind: concrete, value: "xml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding: sval{kind: concrete, value: "yaml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding: sval{kind: concrete, value: "yaml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
			Eval: {
				"-": {
					encoding: sval{kind: dflt, value: "cue", excluded: []string{""}},
					aspects:  aspectSet2,
				},
				".cue": {
					encoding: sval{kind: concrete, value: "cue"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       sval{kind: concrete, value: "code"},
					interpretation: sval{kind: concrete, value: ""},
					aspects:        aspectSet2,
					tags: map[string]sval{
						"lang": {kind: concrete, value: "go"},
					},
				},
				".ini": {
					encoding: sval{kind: concrete, value: "ini"},
					aspects:  aspectSet2,
				},
				".json": {
					encoding: sval{kind: concrete, value: "json"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ldjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".ndjson": {
					encoding: sval{kind: concrete, value: "jsonl"},
					aspects:  aspectSet2,
				},
				".proto": {
					encoding: sval{kind: concrete, value: "proto"},
					aspects:  aspectSet2,
				},
				".textpb": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					aspects:  aspectSet2,
				},
				".toml": {
					encoding: sval{kind: concrete, value: "toml"},
					aspects:  aspectSet2,
				},
				".txt": {
					encoding: sval{kind: concrete, value: "text"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".wasm": {
					encoding: sval{kind: concrete, value: "binary"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet2,
				},
				".xml": {
					encoding: sval{kind: concrete, value: "xml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding: sval{kind: concrete, value: "yaml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding: sval{kind: concrete, value: "yaml"},
					aspects:  aspectSet2,
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
		},
		encodings: [NumModes]map[string]*entry{
			Input: {
				"binary": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"binarypb": {
					encoding: sval{kind: concrete, value: "binarypb"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"code": {
					form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects: aspectSet4,
				},
				"cue": {
					alts: []*entry{
						{
							form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
							aspects: aspectSet4,
						},
						{
							form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
							aspects: aspectSet4,
						},
						{
							aspects: aspectSet5,
						},
					},
				},
				"ini": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"json": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet6,
				},
				"jsonl": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet7,
				},
				"proto": {
					encoding: sval{kind: concrete, value: "proto"},
					form:     sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects:  aspectSet8,
				},
				"text": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"toml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"xml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"yaml": {
					form:    sval{kind: dflt, value: "graph", domain: []string{"dag", "data", "graph"}},
					aspects: aspectSet9,
				},
			},
			Export: {
				"binary": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"binarypb": {
					encoding: sval{kind: concrete, value: "binarypb"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"code": {
					form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects: aspectSet4,
				},
				"cue": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"ini": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"json": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet6,
				},
				"jsonl": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet7,
				},
				"proto": {
					encoding: sval{kind: concrete, value: "proto"},
					form:     sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects:  aspectSet8,
				},
				"text": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"toml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"xml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"yaml": {
					form:    sval{kind: dflt, value: "graph", domain: []string{"dag", "data", "graph"}},
					aspects: aspectSet9,
				},
			},
			Def: {
				"binary": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"binarypb": {
					encoding: sval{kind: concrete, value: "binarypb"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"code": {
					form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects: aspectSet4,
				},
				"cue": {
					form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects: aspectSet4,
				},
				"ini": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"json": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet6,
				},
				"jsonl": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet7,
				},
				"proto": {
					encoding: sval{kind: concrete, value: "proto"},
					form:     sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects:  aspectSet8,
				},
				"text": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"toml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"xml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"yaml": {
					form:    sval{kind: dflt, value: "graph", domain: []string{"dag", "data", "graph"}},
					aspects: aspectSet9,
				},
			},
			Eval: {
				"binary": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"binarypb": {
					encoding: sval{kind: concrete, value: "binarypb"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"code": {
					form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects: aspectSet4,
				},
				"cue": {
					form:    sval{kind: concrete, value: "final"},
					aspects: aspectSet10,
				},
				"ini": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"json": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet6,
				},
				"jsonl": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet7,
				},
				"proto": {
					encoding: sval{kind: concrete, value: "proto"},
					form:     sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
					aspects:  aspectSet8,
				},
				"text": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"textproto": {
					encoding: sval{kind: concrete, value: "textproto"},
					form:     sval{kind: concrete, value: "data"},
					aspects:  aspectSet3,
				},
				"toml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"xml": {
					form:    sval{kind: concrete, value: "data"},
					aspects: aspectSet3,
				},
				"yaml": {
					form:    sval{kind: dflt, value: "graph", domain: []string{"dag", "data", "graph"}},
					aspects: aspectSet9,
				},
			},
		},
		tagInfo: map[string]*entry{
			"auto": {
				encoding:       sval{kind: dflt, value: "json", excluded: []string{""}},
				interpretation: sval{kind: concrete, value: "auto"},
				form:           sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
				aspects:        aspectSet8,
			},
			"binary": {
				encoding: sval{kind: concrete, value: "binary"},
				form:     sval{kind: concrete, value: "data"},
				aspects:  aspectSet2,
			},
			"code": {
				encoding:       sval{kind: concrete, value: "code"},
				interpretation: sval{kind: concrete, value: ""},
				aspects:        aspectSet2,
				tags: map[string]sval{
					"lang": {kind: dflt, value: ""},
				},
			},
			"cue": {
				encoding: sval{kind: concrete, value: "cue"},
				aspects:  aspectSet2,
				boolTags: map[string]bval{
					"compact": dfalse,
				},
			},
			"dag": {
				form:    sval{kind: concrete, value: "dag"},
				aspects: aspectSet2,
			},
			"data": {
				form:    sval{kind: concrete, value: "data"},
				aspects: aspectSet2,
			},
			"go": {
				encoding:       sval{kind: concrete, value: "code"},
				interpretation: sval{kind: concrete, value: ""},
				aspects:        aspectSet2,
				tags: map[string]sval{
					"lang": {kind: concrete, value: "go"},
				},
			},
			"graph": {
				form:    sval{kind: concrete, value: "graph"},
				aspects: aspectSet2,
			},
			"ini": {
				encoding: sval{kind: concrete, value: "ini"},
				aspects:  aspectSet2,
			},
			"json": {
				encoding: sval{kind: concrete, value: "json"},
				aspects:  aspectSet2,
				boolTags: map[string]bval{
					"compact": dfalse,
				},
			},
			"jsonl": {
				encoding: sval{kind: concrete, value: "jsonl"},
				aspects:  aspectSet2,
			},
			"jsonschema": {
				encoding:       sval{kind: dflt, value: "json", excluded: []string{""}},
				interpretation: sval{kind: concrete, value: "jsonschema"},
				form:           sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
				aspects:        aspectSet8,
				boolTags: map[string]bval{
					"openOnlyWhenExplicit": dfalse,
					"strict":               dfalse,
					"strictFeatures":       {kind: ref, reference: "strict"},
					"strictKeywords":       {kind: ref, reference: "strict"},
				},
			},
			"openapi": {
				encoding:       sval{kind: dflt, value: "json", excluded: []string{""}},
				interpretation: sval{kind: concrete, value: "openapi"},
				form:           sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
				aspects:        aspectSet8,
				boolTags: map[string]bval{
					"allSchemas":     dfalse,
					"strict":         dfalse,
					"strictFeatures": {kind: ref, reference: "strict"},
					"strictKeywords": {kind: ref, reference: "strict"},
				},
			},
			"pb": {
				alts: []*entry{
					{
						encoding:       sval{kind: concrete, value: "binarypb"},
						interpretation: sval{kind: concrete, value: ""},
						aspects:        aspectSet2,
					},
					{
						encoding:       sval{kind: concrete, value: "binarypb"},
						interpretation: sval{kind: concrete, value: ""},
					},
					{
						encoding:       sval{kind: constraint, excluded: []string{"binarypb"}},
						interpretation: sval{kind: concrete, value: "pb"},
					},
				},
			},
			"proto": {
				encoding: sval{kind: concrete, value: "proto"},
				aspects:  aspectSet2,
			},
			"schema": {
				form:    sval{kind: concrete, value: "schema"},
				aspects: aspectSet2,
			},
			"text": {
				encoding: sval{kind: concrete, value: "text"},
				form:     sval{kind: concrete, value: "data"},
				aspects:  aspectSet2,
			},
			"textproto": {
				encoding: sval{kind: concrete, value: "textproto"},
				aspects:  aspectSet2,
			},
			"toml": {
				encoding: sval{kind: concrete, value: "toml"},
				aspects:  aspectSet2,
			},
			"xml": {
				encoding: sval{kind: concrete, value: "xml"},
				aspects:  aspectSet2,
				boolTags: map[string]bval{
					"koala": dfalse,
				},
			},
			"yaml": {
				encoding: sval{kind: concrete, value: "yaml"},
				aspects:  aspectSet2,
				boolTags: map[string]bval{
					"indentSequences": dtrue,
				},
			},
		},
		forms: map[string]*entry{
			"dag": {
				form:    sval{kind: constraint, domain: []string{"dag", "data"}},
				aspects: aspectSet11,
			},
			"data": {
				form:    sval{kind: concrete, value: "data"},
				aspects: aspectSet12,
			},
			"final": {
				form:    sval{kind: concrete, value: "final"},
				aspects: aspectSet13,
			},
			"graph": {
				form:    sval{kind: dflt, value: "graph", domain: []string{"dag", "data", "graph"}},
				aspects: aspectSet14,
			},
			"schema": {
				form:    sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
				aspects: aspectSet8,
			},
		},
		interps: map[string]*entry{
			"auto": {
				interpretation: sval{kind: concrete, value: "auto"},
				form:           sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
				aspects:        aspectSet8,
			},
			"jsonschema": {
				encoding:       sval{kind: dflt, value: "json", excluded: []string{""}},
				interpretation: sval{kind: concrete, value: "jsonschema"},
				form:           sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
				aspects:        aspectSet8,
				boolTags: map[string]bval{
					"openOnlyWhenExplicit": dfalse,
					"strict":               dfalse,
					"strictFeatures":       {kind: ref, reference: "strict"},
					"strictKeywords":       {kind: ref, reference: "strict"},
				},
			},
			"openapi": {
				encoding:       sval{kind: dflt, value: "json", excluded: []string{""}},
				interpretation: sval{kind: concrete, value: "openapi"},
				form:           sval{kind: dflt, value: "schema", domain: []string{"final", "graph", "schema"}},
				aspects:        aspectSet8,
				boolTags: map[string]bval{
					"allSchemas":     dfalse,
					"strict":         dfalse,
					"strictFeatures": {kind: ref, reference: "strict"},
					"strictKeywords": {kind: ref, reference: "strict"},
				},
			},
			"pb": {
				interpretation: sval{kind: concrete, value: "pb"},
				form:           sval{kind: concrete, value: "data"},
				aspects:        aspectSet7,
			},
		},
	}
}
