// Code generated by "stringer -type=defIDType -linecomment"; DO NOT EDIT.

package adt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[defIDTypeUnknown-0]
	_ = x[defEmbedding-1]
	_ = x[defReference-2]
	_ = x[defStruct-3]
}

const _defIDType_name = "*EDS"

var _defIDType_index = [...]uint8{0, 1, 2, 3, 4}

func (i defIDType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_defIDType_index)-1 {
		return "defIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _defIDType_name[_defIDType_index[idx]:_defIDType_index[idx+1]]
}
