// Code generated by "stringer -type=vertexStatus"; DO NOT EDIT.

package adt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unprocessed-0]
	_ = x[evaluating-1]
	_ = x[partial-2]
	_ = x[conjuncts-3]
	_ = x[finalized-4]
}

const _vertexStatus_name = "unprocessedevaluatingpartialconjunctsfinalized"

var _vertexStatus_index = [...]uint8{0, 11, 21, 28, 37, 46}

func (i vertexStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_vertexStatus_index)-1 {
		return "vertexStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _vertexStatus_name[_vertexStatus_index[idx]:_vertexStatus_index[idx+1]]
}
