apiVersion: v1
kind: Service
metadata:
  name: waiter
  labels:
    component: frontend
    app: waiter
    domain: prod
spec:
  ports:
  - port: 7080
    targetPort: 7080
    protocol: TCP
    name: client
  selector:
    app: waiter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: waiter
spec:
  replicas: 5
  template:
    metadata:
      labels:
        component: frontend
        app: waiter
        domain: prod
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "7080"
    spec:
      containers:
      - name: waiter
        image: gcr.io/myproj/waiter:v0.3.0
        ports:
        - containerPort: 7080
