// Code generated by generate_server.go; DO NOT EDIT.

package rpcfunc

type serverArgs1[A0 any] struct {
	Arg0 A0
}

// RegisterFunc1 registers a 1-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc1[A0, R any](s *Server, f func(A0) (R, error)) int {
	return register(s,
		func(args serverArgs1[A0]) (R, error) {
			return f(args.Arg0)
		},
	)
}

type serverArgs2[A0, A1 any] struct {
	Arg0 A0
	Arg1 A1
}

// RegisterFunc2 registers a 2-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc2[A0, A1, R any](s *Server, f func(A0, A1) (R, error)) int {
	return register(s,
		func(args serverArgs2[A0, A1]) (R, error) {
			return f(args.Arg0, args.Arg1)
		},
	)
}

type serverArgs3[A0, A1, A2 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
}

// RegisterFunc3 registers a 3-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc3[A0, A1, A2, R any](s *Server, f func(A0, A1, A2) (R, error)) int {
	return register(s,
		func(args serverArgs3[A0, A1, A2]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2)
		},
	)
}

type serverArgs4[A0, A1, A2, A3 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
}

// RegisterFunc4 registers a 4-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc4[A0, A1, A2, A3, R any](s *Server, f func(A0, A1, A2, A3) (R, error)) int {
	return register(s,
		func(args serverArgs4[A0, A1, A2, A3]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3)
		},
	)
}

type serverArgs5[A0, A1, A2, A3, A4 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
}

// RegisterFunc5 registers a 5-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc5[A0, A1, A2, A3, A4, R any](s *Server, f func(A0, A1, A2, A3, A4) (R, error)) int {
	return register(s,
		func(args serverArgs5[A0, A1, A2, A3, A4]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4)
		},
	)
}

type serverArgs6[A0, A1, A2, A3, A4, A5 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
}

// RegisterFunc6 registers a 6-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc6[A0, A1, A2, A3, A4, A5, R any](s *Server, f func(A0, A1, A2, A3, A4, A5) (R, error)) int {
	return register(s,
		func(args serverArgs6[A0, A1, A2, A3, A4, A5]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5)
		},
	)
}

type serverArgs7[A0, A1, A2, A3, A4, A5, A6 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
}

// RegisterFunc7 registers a 7-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc7[A0, A1, A2, A3, A4, A5, A6, R any](s *Server, f func(A0, A1, A2, A3, A4, A5, A6) (R, error)) int {
	return register(s,
		func(args serverArgs7[A0, A1, A2, A3, A4, A5, A6]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6)
		},
	)
}

type serverArgs8[A0, A1, A2, A3, A4, A5, A6, A7 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
	Arg7 A7
}

// RegisterFunc8 registers a 8-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc8[A0, A1, A2, A3, A4, A5, A6, A7, R any](s *Server, f func(A0, A1, A2, A3, A4, A5, A6, A7) (R, error)) int {
	return register(s,
		func(args serverArgs8[A0, A1, A2, A3, A4, A5, A6, A7]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6, args.Arg7)
		},
	)
}

type serverArgs9[A0, A1, A2, A3, A4, A5, A6, A7, A8 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
	Arg7 A7
	Arg8 A8
}

// RegisterFunc9 registers a 9-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc9[A0, A1, A2, A3, A4, A5, A6, A7, A8, R any](s *Server, f func(A0, A1, A2, A3, A4, A5, A6, A7, A8) (R, error)) int {
	return register(s,
		func(args serverArgs9[A0, A1, A2, A3, A4, A5, A6, A7, A8]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6, args.Arg7, args.Arg8)
		},
	)
}

type serverArgs10[A0, A1, A2, A3, A4, A5, A6, A7, A8, A9 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
	Arg7 A7
	Arg8 A8
	Arg9 A9
}

// RegisterFunc10 registers a 10-arg function with the server.
// It returns the function's ID for use in Caller(ID) expressions.
func RegisterFunc10[A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, R any](s *Server, f func(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9) (R, error)) int {
	return register(s,
		func(args serverArgs10[A0, A1, A2, A3, A4, A5, A6, A7, A8, A9]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6, args.Arg7, args.Arg8, args.Arg9)
		},
	)
}
