// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package jsonschema

import (
	"cuelang.org/go/cue"
)

type Crdlike struct {
	ApiVersion string `json:"apiVersion"`

	Kind string `json:"kind"`
}

// Note: this is just the subset of a CRD that we care about for the curation Go logic.
type CRDSpec struct {
	ApiVersion string `json:"apiVersion"`

	Kind string `json:"kind"`

	Spec struct {
		Group string `json:"group"`

		Names struct {
			Kind string `json:"kind"`

			Plural string `json:"plural"`

			Singular string `json:"singular"`
		} `json:"names"`

		Scope string `json:"scope"`

		Versions []struct {
			Name string `json:"name"`

			Schema struct {
				OpenAPIV3Schema cue.Value `json:"openAPIV3Schema"`
			} `json:"schema"`
		} `json:"versions"`
	} `json:"spec"`
}
