// Code generated by generate_func.go; DO NOT EDIT.

package cue

type funcArgs1[A0 any] struct {
	Arg0 A0
}

// PureFunc1 returns a value that holds the function f as a CUE-callable function.
//
// The following documentation applies to all PureFuncN variants.
//
// The function should be side-effect free and deterministic; it will be invoked
// on an "at least once" basis.
//
// Arguments passed to the function are decoded with [Value.Decode];
// the result is encoded with [Context.Encode], with the exception that
// an error result is returned as a CUE error.
func PureFunc1[A0 any, R any](
	f func(A0) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs1[A0]) (R, error) {
			return f(args.Arg0)
		},
		opts,
	)
}

type funcArgs2[A0, A1 any] struct {
	Arg0 A0
	Arg1 A1
}

// PureFunc2 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc2[A0, A1 any, R any](
	f func(A0, A1) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs2[A0, A1]) (R, error) {
			return f(args.Arg0, args.Arg1)
		},
		opts,
	)
}

type funcArgs3[A0, A1, A2 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
}

// PureFunc3 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc3[A0, A1, A2 any, R any](
	f func(A0, A1, A2) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs3[A0, A1, A2]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2)
		},
		opts,
	)
}

type funcArgs4[A0, A1, A2, A3 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
}

// PureFunc4 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc4[A0, A1, A2, A3 any, R any](
	f func(A0, A1, A2, A3) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs4[A0, A1, A2, A3]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3)
		},
		opts,
	)
}

type funcArgs5[A0, A1, A2, A3, A4 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
}

// PureFunc5 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc5[A0, A1, A2, A3, A4 any, R any](
	f func(A0, A1, A2, A3, A4) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs5[A0, A1, A2, A3, A4]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4)
		},
		opts,
	)
}

type funcArgs6[A0, A1, A2, A3, A4, A5 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
}

// PureFunc6 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc6[A0, A1, A2, A3, A4, A5 any, R any](
	f func(A0, A1, A2, A3, A4, A5) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs6[A0, A1, A2, A3, A4, A5]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5)
		},
		opts,
	)
}

type funcArgs7[A0, A1, A2, A3, A4, A5, A6 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
}

// PureFunc7 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc7[A0, A1, A2, A3, A4, A5, A6 any, R any](
	f func(A0, A1, A2, A3, A4, A5, A6) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs7[A0, A1, A2, A3, A4, A5, A6]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6)
		},
		opts,
	)
}

type funcArgs8[A0, A1, A2, A3, A4, A5, A6, A7 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
	Arg7 A7
}

// PureFunc8 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc8[A0, A1, A2, A3, A4, A5, A6, A7 any, R any](
	f func(A0, A1, A2, A3, A4, A5, A6, A7) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs8[A0, A1, A2, A3, A4, A5, A6, A7]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6, args.Arg7)
		},
		opts,
	)
}

type funcArgs9[A0, A1, A2, A3, A4, A5, A6, A7, A8 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
	Arg7 A7
	Arg8 A8
}

// PureFunc9 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc9[A0, A1, A2, A3, A4, A5, A6, A7, A8 any, R any](
	f func(A0, A1, A2, A3, A4, A5, A6, A7, A8) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs9[A0, A1, A2, A3, A4, A5, A6, A7, A8]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6, args.Arg7, args.Arg8)
		},
		opts,
	)
}

type funcArgs10[A0, A1, A2, A3, A4, A5, A6, A7, A8, A9 any] struct {
	Arg0 A0
	Arg1 A1
	Arg2 A2
	Arg3 A3
	Arg4 A4
	Arg5 A5
	Arg6 A6
	Arg7 A7
	Arg8 A8
	Arg9 A9
}

// PureFunc10 returns a value that holds the function f as a CUE-callable function.
//
// See [PureFunc1] for more information.
func PureFunc10[A0, A1, A2, A3, A4, A5, A6, A7, A8, A9 any, R any](
	f func(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9) (R, error),
	opts ...FuncOption,
) Value {
	return pureFunc(
		func(args funcArgs10[A0, A1, A2, A3, A4, A5, A6, A7, A8, A9]) (R, error) {
			return f(args.Arg0, args.Arg1, args.Arg2, args.Arg3, args.Arg4, args.Arg5, args.Arg6, args.Arg7, args.Arg8, args.Arg9)
		},
		opts,
	)
}
