//go:build ignore

package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"text/template"
)

const tmplText = `
// Code generated by generate_func.go; DO NOT EDIT.

package cue
{{range $n0 := .}}{{$n := add1 $n0}}
type funcArgs{{$n}}[{{range $i := $n}}{{if $i}}, {{end}}A{{$i}}{{end}} any] struct {
{{- range $i := $n}}
	Arg{{$i}} A{{$i}}
{{- end}}
}
{{if eq $n 1}}
// NewPureFunc1 returns a value that holds the function f as a CUE-callable function.
//
// The following documentation applies to all PureFuncN variants.
//
// The function should be side-effect free and deterministic; it will be invoked
// on an "at least once" basis.
//
// Arguments passed to the function are decoded with [Value.Decode];
// the result is encoded with [Context.Encode], with the exception that
// an error result is returned as a CUE error.
{{- else}}
// NewPureFunc{{$n}} returns a value that holds the function f as a CUE-callable function.
//
// See [NewPureFunc1] for more information.
{{- end}}
func NewPureFunc{{$n}}[{{range $i := $n}}{{if $i}}, {{end}}A{{$i}}{{end}} any, R any](
	f func({{range $i := $n}}{{if $i}}, {{end}}A{{$i}}{{end}}) (R, error),
	opts ...FuncOption,
) Value {
	return newPureFunc(
		func(args funcArgs{{$n}}[{{range $i := $n}}{{if $i}}, {{end}}A{{$i}}{{end}}]) (R, error) {
			return f({{range $i := $n}}{{if $i}}, {{end}}args.Arg{{$i}}{{end}})
		},
		opts,
	)
}
{{end}}
`

const maxArity = 10

func main() {
	funcTmpl := template.Must(template.New("funcs").Funcs(template.FuncMap{
		"add1": func(i int) int { return i + 1 },
	}).Parse(tmplText))

	var buf bytes.Buffer
	if err := funcTmpl.Execute(&buf, maxArity); err != nil {
		panic(err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		os.Stderr.Write(buf.Bytes())
		log.Fatal(err)
	}
	if err := os.WriteFile("func_gen.go", src, 0o666); err != nil {
		log.Fatal(err)
	}
}
