apiVersion: v1
kind: Service
metadata:
  name: souschef
  labels:
    app: souschef
    component: kitchen
    domain: prod
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: client
  selector:
    app: souschef
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: souschef
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: souschef
        component: kitchen
        domain: prod
    spec:
      containers:
      - name: souschef
        image: gcr.io/myproj/souschef:v0.5.3
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /debug/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 3