// Code generated by "stringer -type=EventKind -linecomment"; DO NOT EDIT.

package httplog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoEvent-0]
	_ = x[KindClientSendRequest-1]
	_ = x[KindClientRecvResponse-2]
}

const _EventKind_name = "NoEventhttp client->http client<-"

var _EventKind_index = [...]uint8{0, 7, 20, 33}

func (i EventKind) String() string {
	if i < 0 || i >= EventKind(len(_EventKind_index)-1) {
		return "EventKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventKind_name[_EventKind_index[i]:_EventKind_index[i+1]]
}
