// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go cuelang.org/go/cmd/cue/cmd/testdata/code/go/pkg1

package pkg1

import "cuelang.org/go/cmd/cue/cmd/testdata/code/go/pkg2"

#MyBarzer: pkgtwo.#Barzer
